version: '3.7'

services:
  api:
    build: ./src/BE/
    container_name: api
    command: bash -c "alembic upgrade head && uvicorn iris_backend:app --reload --host 0.0.0.0 --port 8000"
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB"]
      test: ["CMD-SHELL", "pg_isready -h postgres -p 5432 -U alifvianmarco -d password"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./src/BE/:/app_backend/
      - ./alembic.ini:/app_backend/
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - backend
    env_file:
      - src/BE/.env.docker

  streamlit_service:
    build: ./src/FE/
    container_name: feservice
    command: streamlit run iris_frontend.py
    volumes:
      - ./src/FE/:/app_frontend/
    ports:
      - 8501:8501
    links:
      - api
    # env_file:
    #   - src/BE/.env.docker

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: alifvianmarco
      POSTGRES_PASSWORD: password
      POSTGRES_DB: irisdb
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    # restart: always
    env_file:
      - src/BE/.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge