"""init

Revision ID: 466313f539b9
Revises: 8854a5d6a666
Create Date: 2024-01-24 22:04:26.509685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466313f539b9'
down_revision: Union[str, None] = '8854a5d6a666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iris')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iris',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sepal_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('petal_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sepal_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('petal_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='iris_pkey')
    )
    # ### end Alembic commands ###
