channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - numpy==1.26.2
  - packaging==23.2
  - pyyaml==6.0.1
  - scikit-learn==1.2.1
  - scipy==1.11.4
name: mlflow-env
